### PR TITLE
fix comment handling

### LINKED ISSUE #149: statement separator don't treat comments as a token separator
The statement separator implementation treat comments as empty but it should be treated as a kind of a token separator as like whitespaces.
This behavior can make query execution an error or even change the meaning of the query.

## Example

spanner-cli evaluate `SELECT 0x1/**/A` as `SELECT 0x1A`.

```
$ spanner-cli -d ${DATABASE} --execute='SELECT 0x1/**/A' -t                                             
+----+
|    |
+----+
| 26 |
+----+
```

### Expected behavior
It should be evaluated as `SELECT 0x1 A`(equivalent of `SELECT 0x1 AS A`).

```
$ gcloud spanner databases execute-sql ${DATABASE} --sql='SELECT 0x1/**/A'               
A
1
```

### Related specification

https://cloud.google.com/spanner/docs/reference/standard-sql/lexical?hl=en
> **You can separate tokens with comments** or whitespace such as spaces, backspaces, tabs, or newlines.

### PR DESCRIPTION
**Pull request by apstndb**
This PR changes comment handling in the statement separator.
Comments are replaced by a single whitespace if the next character is not whitespaces.

It may be better to check previous character of the comment but it is not easy without changing structure.

fixes #149

### CODE REVIEW

File: separator.go [hunk 1]
```diff
@@ -154,26 +154,40 @@ func (s *separator) consumeStringDelimiter() string {
...
 			terminate = "*/"
+			found = true
 			i += 2
-		}
+		} else {
+			// no comment found
 
-		// no comment found
-		if terminate == "" {
+			// emit space if comments are found and the next character is not a whitespace
```
Comment (yfuruyama) [inline separator.go:180]: I have two questions.

1. Initially, this was a little bit difficult for me to understand because the block under `if found && i < len(s.str) {` is executed in the 2nd iteration of the outer loop. Doesn't it work if we just put `s.sb.WriteRune(' ')` at [here](https://github.com/cloudspannerecosystem/spanner-cli/blob/v0.9.16/separator.go#L189) and [here](https://github.com/cloudspannerecosystem/spanner-cli/blob/v0.9.16/separator.go#L195)? Both lines are points where the comment termination found.
2. It looks like the whitespace is not inserted if the next character is a whitespace. Do we need to care about whether the next character is a whitespace or not? Why not simply converting "a comment" to the "whitespace"?

Comment (apstndb) [reply separator.go:180]: I think we need to discuss about expected behavior as a design decision.

- If we can think only token separation.
  - We can always put the whitespace.
- If we need to concern about query text in query stats, audit logs, etc.
  - We may need to define expected behavior.


Need to consider about end of string?
e.g.
`'SELECT 1# comment' → 'SELECT 1' or 'SELECT 1 '`?


Can it be interpret as `SELECT   1` and `SELECT 2`?
e.g.
```
# comment;
SELECT /* comment */ 1; --comment
SELECT 2;/* comment */
```

Comment (yfuruyama) [reply separator.go:180]: The current implementation is already stripping the comment from the query, so I think users won't expect the query is intact when writing a comment in the query string.

Having said that, it might be good idea to change the current implementation to keep the comment in query string. Then we can defer to the Spanner server side for the handling of comment characters in a query string. (It looks like Spanner keeps the comment characters in query stats.)

Comment (apstndb) [reply separator.go:180]: May be a solution.
1. Separate queries (preserving queries)
2. Strip comments and detect kind of statement
3.   a. execute stripped DDL
      b. execute raw DML/SELECT

Comment (yfuruyama) [reply separator.go:180]: Sounds good! Is it possible to implement the solution in https://github.com/apstndb/gsqlsep and switch to use it from spanner-cli?

Comment (apstndb) [reply separator.go:180]: I'd like to PoC using gsqlsep.

**Comment by apstndb** [comment]
I have experimentally replaced statement separator with gsqlsep and implement comment preserving(only `SelectStatement` and `DmlStatement`)

File: cli.go [hunk 2]
```diff
@@ -516,3 +520,7 @@ func handleInterrupt(cancel context.CancelFunc) {
 	<-c
 	cancel()
 }
+
+func stripComments(input string) string {
```
Comment (yfuruyama) [inline cli.go:524]: Just a random idea.

## Random idea 1

What do you think about changing `gsqlsep.InputStatement` as follows,

```
type InputStatement struct {
	Statement                string
	StatementWithoutComment  string
	Terminator               string
}
```

and use `StatementWithoutComment` for input match and `Statement` for other use case? Then we don't need to call `gsqlsep.Separate...` functions in two difference places.

## Random idea 2

What do you think about adding `StripComments()` method to `gsqlsep.InputStatement`?

File: separator.go [hunk 3]
```diff
@@ -16,284 +16,28 @@
...
-	case delimiterHorizontal:
-		return ";"
-	case delimiterVertical:
-		return `\G`
-	}
-	return ""
+	delim     string
 }
 
 func separateInput(input string) []inputStatement {
```
Comment (yfuruyama) [inline separator.go:34]: If we keep this function, why not calling this function in other places? (not directly call gsqlsep functions)

**Review by yfuruyama — COMMENTED** [review]
Thanks for implementing with gsqlsep!

**Comment by apstndb** [comment]
I added InputStatement.StripComments into gsqlsep and enhanced `separateInput` in spanner-cli.
gsqlsep is no longer referenced outside of `separateInput`.

File: separator.go [hunk 4]
```diff
@@ -16,284 +16,29 @@
...
-	if s.sb.Len() > 0 {
-		if str := strings.TrimSpace(s.sb.String()); len(str) > 0 {
-			statements = append(statements, inputStatement{
-				statement: str,
-				delim:     delimiterUndefined,
-			})
-			s.sb.Reset()
-		}
+	var result []inputStatement
+	for _, stmt := range gsqlsep.SeparateInputPreserveComments(input, `\G`) {
```
Comment (yfuruyama) [inline separator.go:35]:
```suggestion
	for _, stmt := range gsqlsep.SeparateInputPreserveComments(input, delimiterVertical) {
```

File: separator.go [hunk 5]
```diff
@@ -16,284 +16,29 @@
...
+		stmt := stmt
```
Comment (yfuruyama) [inline separator.go:36]: What is the reason we need to capture this in a local variable?

File: separator.go (hunk 4 above)
Comment (apstndb) [reply separator.go:35]: 👍

File: separator.go (hunk 5 above)
Comment (apstndb) [reply separator.go:36]: I don't think it is needed.
